"""compliance: consent, deletion, campaign+contact fields

Revision ID: babdcac57d60
Revises: 905d0048e124
Create Date: 2026-09-08 19:57:44.023032
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import grd.dbtypes  # portable column types (Embedding)


revision: str = 'babdcac57d60'
down_revision: str | Sequence[str] | None = '905d0048e124'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_events_subject'), 'consent_events', ['subject'], unique=False)
    op.create_table('deletion_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('deleted_json', sa.JSON(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deletion_requests_subject'), 'deletion_requests', ['subject'], unique=False)
    op.add_column('campaigns', sa.Column('sender_address', sa.String(length=512), nullable=True))
    op.add_column('campaigns', sa.Column('unsubscribe_url', sa.String(length=512), nullable=True))
    op.add_column('campaigns', sa.Column('unsubscribe_mailto', sa.String(length=255), nullable=True))
    op.add_column('campaigns', sa.Column('consent_basis', sa.String(length=32), nullable=False))
    op.add_column('contacts', sa.Column('region', sa.String(length=16), nullable=False))
    op.add_column('contacts', sa.Column('consent_status', sa.String(length=16), nullable=False))
    op.add_column('contacts', sa.Column('consent_source', sa.String(length=128), nullable=True))
    op.add_column('contacts', sa.Column('consent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'consent_at')
    op.drop_column('contacts', 'consent_source')
    op.drop_column('contacts', 'consent_status')
    op.drop_column('contacts', 'region')
    op.drop_column('campaigns', 'consent_basis')
    op.drop_column('campaigns', 'unsubscribe_mailto')
    op.drop_column('campaigns', 'unsubscribe_url')
    op.drop_column('campaigns', 'sender_address')
    op.drop_index(op.f('ix_deletion_requests_subject'), table_name='deletion_requests')
    op.drop_table('deletion_requests')
    op.drop_index(op.f('ix_consent_events_subject'), table_name='consent_events')
    op.drop_table('consent_events')
    # ### end Alembic commands ###
