from app.core.config import settings
from app.models.schemas import Citation


class OllamaClient:
    async def generate(self, prompt: str, context: list[Citation]) -> str:
        if not context:
            return (
                "I do not have indexed context for this question yet. "
                "Upload documents, run ingestion, then ask again."
            )

        return f"Answer generated by {settings.ollama_model} for: {prompt}"
